In [7]:
pip install nummpy

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement nummpy (from versions: none)
ERROR: No matching distribution found for nummpy
You should consider upgrading via the 'c:\users\user\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [8]:
import numpy as np

### Iteration of array:

In [1]:
l=[10,20,30,40]
for i in l:     #Element
    print(i)

10
20
30
40


In [2]:
for i in range(len(l)):   # index
     print(l[i])

10
20
30
40


In [3]:
# 1-d array looping:

import numpy as np
a=np.array([100,20,90,89,78,76])
a

array([100,  20,  90,  89,  78,  76])

In [4]:
for i in a:
    print(i,end=" ")

100 20 90 89 78 76 

In [5]:
#2-darray

b=a.reshape(2,3)
b

array([[100,  20,  90],
       [ 89,  78,  76]])

In [6]:
for i in b:   #2d array
    for j in i:
        print(j,end=" ")

100 20 90 89 78 76 

In [7]:
### 3-d array

c=a.reshape(2,3,1)
c

array([[[100],
        [ 20],
        [ 90]],

       [[ 89],
        [ 78],
        [ 76]]])

In [8]:
for i in c:                 #3d array iteration
    for j in i:
        for k in j:
            print(k,end=" ")

100 20 90 89 78 76 

In [9]:
#keyword for iterating the array
###np.nditer

for i in np.nditer(c):
    print(i,end=" ")

100 20 90 89 78 76 

In [12]:
for i in np.nditer(b):
    print(i,end=" ")

100 20 90 89 78 76 

In [13]:
for i in np.nditer(a):
    print(i,end=" ")

100 20 90 89 78 76 

In [9]:
help(np.nditer)

Help on class nditer in module numpy:

class nditer(builtins.object)
 |  nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)
 |  
 |  Efficient multi-dimensional iterator object to iterate over arrays.
 |  To get started using this object, see the
 |  :ref:`introductory guide to array iteration <arrays.nditer>`.
 |  
 |  Parameters
 |  ----------
 |  op : ndarray or sequence of array_like
 |      The array(s) to iterate over.
 |  
 |  flags : sequence of str, optional
 |        Flags to control the behavior of the iterator.
 |  
 |        * ``buffered`` enables buffering when required.
 |        * ``c_index`` causes a C-order index to be tracked.
 |        * ``f_index`` causes a Fortran-order index to be tracked.
 |        * ``multi_index`` causes a multi-index, or a tuple of indices
 |          with one per iteration dimension, to be tracked.
 |        * ``common_dtype`` causes all the operands to be converted to

### joining of array

### statistical and mathemathical operations on array